name: streaming_radio_flutter_plugin
description: This is a simple radio streaming plugin, with notification in foreground.
version: 3.0.2
email: cristiantorrado@gmail.com
homepage: "https://cristiantorrado.github.io/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.cristiantorrado.streaming
        pluginClass: StreamingPlugin
      ios:
        pluginClass: StreamingPlugin
